name: "CI"
on:
  push:
    branches: ["main", "cache"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: dep
        run: |
          echo "init"
          sudo apt-get update
          sudo apt-get install -y gcc make
          sudo apt-get install -y libglib2.0-dev 
          sudo apt-get install -y timelimit

      - name: build
        run: |
          make

      - name: run proxy
        run: |
          timelimit -t 30 -s 2 -T 100 ./build/proxy --threads 110 --mode cache --port 8080 &


      - name: run test
        run: |
          cd tests
          ./4-parallel-clients.sh --port 8080 --url http://xcal1.vodafone.co.uk/5MB.zip --requests 100  --timeout 70
          ./2-concurrent-batches.sh --port 8080 --url http://xcal1.vodafone.co.uk/5MB.zip --requests 50 --timeout 30 --concurrency 25



          
   
   
  
    
